package net.unknownuser.networking.game;

public enum MessageType {
	CHAT_MESSAGE,
	SYNC_PLAYERS,
	MOVE,
	SET_ID,
	SET_PREFERENCES,
	NEW_PLAYER,
	DELETE_PLAYER,
	SET_COLOUR,
	MOVE_REJECTED,
	REQUEST_POSITION,
	SET_POSITION,
	SYNC_PLAYER_POSITIONS
}
